modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/hammertater/treechop/issues"

[[mods]]
modId="treechop"
version="${file.jarVersion}"
displayName="HT's TreeChop"
updateJSONURL="https://raw.githubusercontent.com/hammertater/treechop/main/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/treechop"
logoFile="logo.png"
credits="This one goes out to all the lumberjacks."
authors="HammerTater"
description="Makes trees more choppable."

[[dependencies.treechop]]
modId="pmmo"
mandatory=false
